spring.application.name=miniright

## 로그 관련 설정
# 로그 색상
spring.output.ansi.enabled=always
# 로그 레벨 설정
logging.level.root=info

# Mybatis 로그
logging.level.com.pknu26.miniright.mapper=debug
logging.level.org.mybatis=debug
logging.level.java.sql=debug

## Oracle DB 설정
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=community
spring.datasource.password=java12345

## MyBatis 설정 
# MyBatis 쿼리 저장 위치 -- 이거 추가해야 xml이 굴러가용
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.pknu26.miniright.dto
mybatis.configuration.map-underscore-to-camel-case=true

## Thymeleaf 설정 - 개발 때만 추가
spring.thymeleaf.cache=false

## 파일 업로드 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## 에러 페이지 설정
server.error.whitelabel.enabled=false
server.error.include-exception=false
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

## 같은 와이파이의 다른 PC에서 접속 가능하도록 설정
server.address=0.0.0.0
server.port=8080

## 이미지 업로드 저장 위치
file.upload-dir=D:/java-miniproject-2026/miniright/uploads

## 한국 시간 반영
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET TIME_ZONE = '+09:00'