-- 시퀀스 삭제 필요 시 // 세미콜론 하나씩 실행 요망
-- 회원(users) 번호 시퀀스 삭제
DROP SEQUENCE SEQ_USERS_ID;

-- 거래게시판(B_BOARD) 시퀀스 삭제
DROP SEQUENCE SEQ_B_POST_ID;

-- 자유게시판(C_BOARD) 시퀀스 삭제
DROP SEQUENCE SEQ_C_POST_ID;

-- 카테고리(CATEGORY) 시퀀스 삭제
DROP SEQUENCE SEQ_CATEGORY_ID;

-- 댓글(COMMENTS) 시퀀스 삭제
DROP SEQUENCE SEQ_COMMENT_ID;

-- 답글(REPLY) 시퀀스 삭제
DROP SEQUENCE SEQ_REPLY_ID;



-- 회원(users) 번호 시퀀스 쿼리문
CREATE SEQUENCE SEQ_USERS_ID
START WITH 100 -- 안전하게 100부터 하자
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 거래게시판(B_BOARD) 시퀀스 쿼리문
CREATE SEQUENCE B_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 자유게시판(C_BOARD) 시퀀스 쿼리문
CREATE SEQUENCE C_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 카테고리(CATEGORY) 시퀀스 쿼리문
CREATE SEQUENCE SEQ_CATEGORY_ID 
START WITH 1 
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 댓글(COMMENTS) 시퀀스 쿼리문
CREATE SEQUENCE SEQ_COMMENT_ID 
START WITH 1 
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 답글(REPLY) 시퀀스 쿼리문
CREATE SEQUENCE SEQ_REPLY_ID 
START WITH 1 
INCREMENT BY 1
NOCACHE
NOCYCLE;



--- buildenough start ---

-- 댓글 시퀀스
CREATE SEQUENCE COMMENTS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--- buildenough end ---