-- 테이블 삭제 필요 시 // 세미콜론 하나씩 실행 요망
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE B_BOARD CASCADE CONSTRAINTS;
DROP TABLE C_BOARD CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

-- 카테고리 테이블
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

-- 회원 테이블
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    LOGIN_ID VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(30) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE
);

-- 거래게시판 테이블
CREATE TABLE B_BOARD (
    POST_ID NUMBER PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT fk_bboard_category FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT fk_bboard_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 자유게시판 테이블
CREATE TABLE C_BOARD (
    POST_ID NUMBER PRIMARY KEY, 
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    WRITER VARCHAR2(100), 
    VIEW_COUNT NUMBER DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    USER_ID NUMBER NOT NULL, 
    CONSTRAINT fk_cboard_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 댓글 테이블
CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    CONTENTS VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE,
    POST_ID NUMBER NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT fk_comment_category FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT fk_comment_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT fk_comment_bboard FOREIGN KEY (POST_ID) REFERENCES B_BOARD(POST_ID)
);

-- 답글 테이블
CREATE TABLE REPLY (
    REPLY_ID NUMBER PRIMARY KEY,
    CONTENTS VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT  DATE,
    POST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT fk_reply_cboard FOREIGN KEY (POST_ID) REFERENCES C_BOARD(POST_ID) ON DELETE CASCADE,
    CONSTRAINT fk_reply_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 이미지 테이블 / 메인화면 계획 중단으로 인해 필요없어진 DB
-- CREATE TABLE IMAGE (
--     IMAGE_ID NUMBER PRIMARY KEY,
--     IMAGE_KEY VARCHAR2(100) NOT NULL,
--     IMAGE_PATH VARCHAR2(500) NOT NULL,
--     USE_YN CHAR(1) NOT NULL,
--     CREATED_AT DATE NOT NULL
--  );