-- =====================================================
-- 오른팔조 미니프로젝트 DB 초기화 및 생성 스크립트
-- COMMUNITY 계정에서 실행
-- DBeaver 기준: Alt + X로 전체 실행
-- =====================================================


-- =====================================================
-- 1. 기존 테이블 삭제
-- 없다는 오류가 나오면 Skip all 눌러도 됨
-- =====================================================

DROP TABLE COMMENTS CASCADE CONSTRAINTS PURGE;
DROP TABLE REPLY CASCADE CONSTRAINTS PURGE;
DROP TABLE B_BOARD CASCADE CONSTRAINTS PURGE;
DROP TABLE C_BOARD CASCADE CONSTRAINTS PURGE;
DROP TABLE USERS CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORY CASCADE CONSTRAINTS PURGE;


-- =====================================================
-- 2. 기존 시퀀스 삭제
-- 없다는 오류가 나오면 Skip all 눌러도 됨
-- =====================================================

DROP SEQUENCE SEQ_USERS_ID;
DROP SEQUENCE B_BOARD_SEQ;
DROP SEQUENCE C_BOARD_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE SEQ_REPLY_ID;

-- 예전 스크립트에서 사용하던 시퀀스 정리용
DROP SEQUENCE SEQ_B_POST_ID;
DROP SEQUENCE SEQ_C_POST_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_COMMENT_ID;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE USER_ACCOUNT_SEQ;


-- =====================================================
-- 3. 테이블 생성
-- =====================================================

-- 카테고리 테이블
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL
);

-- 회원 테이블
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    LOGIN_ID VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(30) NOT NULL,
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATED_AT DATE
);

-- 자유게시판 테이블
CREATE TABLE C_BOARD (
    POST_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    WRITER VARCHAR2(100),
    ANONYMOUS NUMBER(1) DEFAULT 0 NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATED_AT DATE,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_CBOARD_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 거래게시판 테이블
CREATE TABLE B_BOARD (
    POST_ID NUMBER PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENTS CLOB NOT NULL,
    VIEW_COUNT NUMBER DEFAULT 0,
    IMAGE_PATH VARCHAR2(500),
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATED_AT DATE,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_BBOARD_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_BBOARD_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

-- 거래게시판 댓글 테이블
CREATE TABLE COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    CONTENTS VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATED_AT DATE,
    POST_ID NUMBER NOT NULL,
    CATEGORY_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_COMMENT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_COMMENT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),
    CONSTRAINT FK_COMMENT_BBOARD
        FOREIGN KEY (POST_ID)
        REFERENCES B_BOARD(POST_ID)
        ON DELETE CASCADE
);

-- 자유게시판 댓글/답글 테이블
CREATE TABLE REPLY (
    REPLY_ID NUMBER PRIMARY KEY,
    CONTENTS VARCHAR2(1000) NOT NULL,
    WRITER VARCHAR2(100),
    CREATED_AT DATE DEFAULT CURRENT_DATE NOT NULL,
    UPDATED_AT DATE,
    POST_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_REPLY_CBOARD
        FOREIGN KEY (POST_ID)
        REFERENCES C_BOARD(POST_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_REPLY_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE
);


-- =====================================================
-- 4. 시퀀스 생성
-- 현재 코드에서 사용하는 이름 기준
-- =====================================================

-- 회원 PK용
CREATE SEQUENCE SEQ_USERS_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 자유게시판 PK용
CREATE SEQUENCE C_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 거래게시판 PK용
CREATE SEQUENCE B_BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 거래게시판 댓글 PK용
CREATE SEQUENCE COMMENTS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 자유게시판 댓글/답글 PK용
CREATE SEQUENCE SEQ_REPLY_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


-- =====================================================
-- 5. 카테고리 기본 데이터
-- =====================================================

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (1, '삽니다');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (2, '팝니다');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (3, '예약중');

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (4, '판매완료');

COMMIT;